name: Test check.sh in Debian

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Debian in Docker
        run: |
          docker run --name debian-test -d -it debian:bookworm bash
          docker exec debian-test apt update && docker exec debian-test apt install -y sudo curl

      - name: Copy check.sh into Container
        run: |
          docker cp scripts/check.sh debian-test:/check.sh
          docker exec debian-test chmod +x /check.sh

      - name: Run check.sh
        run: |
          docker exec debian-test bash -c "/check.sh"

      - name: Check Redis Status
        run: |
          docker exec debian-test redis-cli ping | grep -q "PONG"

      - name: Check Neo4j Status
        run: |
          docker exec debian-test neo4j status | grep -q "is running"

      - name: Check llama-server Health
        run: |
          docker exec debian-test curl -s -X GET http://localhost:8080/health | grep -q '"status":"ok"'

      - name: Cleanup
        if: always()
        run: docker stop debian-test && docker rm debian-test
